[package]
name = "lcov-summarize-markdown"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lcov = "0.8.1"
miette = { version = "5.10.0", features = ["fancy", "backtrace"] }
